# Generated by Django 3.1.2 on 2020-10-11 19:50

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('shortcode', models.CharField(default=api.utils.random_string, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TinyURLStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('shortcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tinyurl')),
            ],
        ),
    ]
